export const Questions = [
    {
      prompt: 'Which of the following is a non metal that remains liquid at room temperature?',
      optionA: 'Phosphorous',
      optionB: 'Bromine',
      optionC: 'Chlorine',
      optionD: 'Helium',
      asnwer: 'B',
    },
    {
      prompt: 'Which of this is not a programming language?',
      optionA: 'Python',
      optionB: 'JavaScript',
      optionC: 'MC-03',
      optionD: 'Java',
      asnwer: 'C',
    },
    
    {
      prompt: 'When is the World Population Day observed?',
      optionA: 'May 31',
      optionB: 'October 4',
      optionC: 'July 11',
      optionD: 'December 10',
      asnwer: 'C',
    },
    {
      prompt: 'For which of the following disciplines is Nobel Prize awarded?',
      optionA: 'Physics and Chemistry',
      optionB: 'Physiology or Medicine',
      optionC: 'Literature, Peace and Economics',
      optionD: 'All of the above',
      asnwer: 'D',
    },
    {
      prompt: 'FFC stands for',
      optionA: 'Foreign Finance Corporation',
      optionB: 'Film Finance Corporation',
      optionC: 'Federation of Football Council',
      optionD: 'None of the above',
      asnwer: 'B',
    },
    {
      prompt: '50 times of 8 is equal to:',
      optionA: '80',
      optionB: '400',
      optionC: '800',
      optionD: '4000',
      asnwer: 'B',
    },
   
    {
      prompt: 'In which movie did Preity Zinta make her debut?',
      optionA: 'Soilder',
      optionB: 'Dil Se',
      optionC: 'Kya Kehna',
      optionD: 'None of the above',
      asnwer: 'B',
    },
    {
      prompt: 'Which of this is not a javascript framework?',
      optionA: 'React',
      optionB: 'Angular',
      optionC: 'Vue',
      optionD: 'Java',
      asnwer: 'D',
    },
    {
      prompt: 'Which of the following is used in pencils?',
      optionA: 'Graphite',
      optionB: 'Silicon',
      optionC: 'Charcoal',
      optionD: 'Phosphorous',
      asnwer: 'A',
    },
    {
      prompt: 'In React.js which one of the following is used to create a class for Inheritance ?',
      optionA: 'Create',
      optionB: 'Delete',
      optionC: 'Inherits',
      optionD: 'Extends',
      asnwer: 'D',
    },
    {
      prompt: 'What is the next prime number after 5?',
      optionA: '6',
      optionB: '7',
      optionC: '9',
      optionD: '11',
      asnwer: 'B',
    },
  ];